/**
 * Mock training & evaluation tasks for empty-state previewing.
 * Used by Models and Evaluations pages when the backend returns no data,
 * so designers can review the UI with realistic content.
 */

const day = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();

export const MOCK_TRAINING_TASKS: any[] = [
  {
    id: 9001,
    name: "Road signs v2 — yolo11m",
    status: "completed",
    progress: 100,
    created_at: day(1),
    task_metadata: {
      model_type: "yolo11m.pt",
      model_config: { model: "yolo11m.pt" },
      training_params: { epochs: 100, imgsz: 640, batch: 16 },
      results: { metrics: { "metrics/mAP50(B)": 0.912, "metrics/mAP50-95(B)": 0.671 } },
    },
  },
  {
    id: 9002,
    name: "Crops segmentation — yolo11s-seg",
    status: "running",
    progress: 47,
    created_at: day(0),
    task_metadata: {
      model_type: "yolo11s-seg.pt",
      model_config: { model: "yolo11s-seg.pt" },
      training_params: { epochs: 80, imgsz: 1024, batch: 8 },
    },
  },
  {
    id: 9003,
    name: "Pothole detection — yolo11n",
    status: "completed",
    progress: 100,
    created_at: day(4),
    task_metadata: {
      model_type: "yolo11n.pt",
      model_config: { model: "yolo11n.pt" },
      training_params: { epochs: 150, imgsz: 640, batch: 32 },
      results: { metrics: { "metrics/mAP50(B)": 0.847 } },
    },
  },
  {
    id: 9004,
    name: "Car damage — rtdetr-l",
    status: "failed",
    progress: 23,
    created_at: day(2),
    error_message: "CUDA out of memory. Reduce batch size or imgsz.",
    task_metadata: {
      model_type: "rtdetr-l.pt",
      model_config: { model: "rtdetr-l.pt" },
      training_params: { epochs: 100, imgsz: 1280, batch: 16 },
    },
  },
  {
    id: 9005,
    name: "Aerial trees — yolo11x",
    status: "pending",
    progress: 0,
    created_at: day(0),
    task_metadata: {
      model_type: "yolo11x.pt",
      model_config: { model: "yolo11x.pt" },
      training_params: { epochs: 200, imgsz: 1024, batch: 4 },
    },
  },
  {
    id: 9006,
    name: "Solar panels — yolo11s",
    status: "stopped",
    progress: 62,
    created_at: day(7),
    task_metadata: {
      model_type: "yolo11s.pt",
      model_config: { model: "yolo11s.pt" },
      training_params: { epochs: 120, imgsz: 640, batch: 16 },
    },
  },
];

export const MOCK_EVALUATION_TASKS: any[] = [
  {
    id: 8001,
    name: "Road signs v2 — test set",
    status: "completed",
    progress: 100,
    created_at: day(1),
    task_metadata: {
      model_type: "yolo11m.pt",
      training_task_name: "Road signs v2",
      dataset_name: "Road signs (test)",
      collection_name: "RGB",
      annotation_file_name: "road_signs_v1.coco.json",
      results: {
        precision: 0.913,
        recall: 0.876,
        f1_score: 0.894,
        images_processed: 412,
        predictions_count: 2387,
        has_ground_truth: true,
      },
    },
  },
  {
    id: 8002,
    name: "Pothole detection — city A",
    status: "running",
    progress: 64,
    created_at: day(0),
    task_metadata: {
      model_type: "yolo11n.pt",
      training_task_name: "Pothole detection",
      dataset_name: "Potholes — City A",
    },
  },
  {
    id: 8003,
    name: "Crops seg — multi-region",
    status: "completed",
    progress: 100,
    created_at: day(3),
    task_metadata: {
      model_type: "yolo11s-seg.pt",
      training_task_name: "Crops segmentation",
      is_multi_dataset: true,
      child_task_ids: [8101, 8102, 8103],
      dataset_names: ["Region A", "Region B", "Region C"],
      aggregate_results: {
        precision: 0.802,
        recall: 0.771,
        f1_score: 0.786,
        has_ground_truth: true,
      },
    },
  },
  {
    id: 8101,
    name: "Crops seg — Region A",
    status: "completed",
    progress: 100,
    created_at: day(3),
    task_metadata: {
      parent_task_id: 8003,
      model_type: "yolo11s-seg.pt",
      dataset_name: "Region A",
      collection_name: "RGB",
      annotation_file_name: "crops_v3.coco.json",
      results: { precision: 0.81, recall: 0.78, f1_score: 0.795, images_processed: 220, predictions_count: 1502, has_ground_truth: true },
    },
  },
  {
    id: 8102,
    name: "Crops seg — Region B",
    status: "completed",
    progress: 100,
    created_at: day(3),
    task_metadata: {
      parent_task_id: 8003,
      model_type: "yolo11s-seg.pt",
      dataset_name: "Region B",
      annotation_file_name: "crops_v3.coco.json",
      results: { precision: 0.79, recall: 0.76, f1_score: 0.775, images_processed: 180, predictions_count: 1244, has_ground_truth: true },
    },
  },
  {
    id: 8103,
    name: "Crops seg — Region C",
    status: "completed",
    progress: 100,
    created_at: day(3),
    task_metadata: {
      parent_task_id: 8003,
      model_type: "yolo11s-seg.pt",
      dataset_name: "Region C",
      annotation_file_name: "crops_v3.coco.json",
      results: { precision: 0.805, recall: 0.773, f1_score: 0.789, images_processed: 195, predictions_count: 1357, has_ground_truth: true },
    },
  },
  {
    id: 8004,
    name: "Car damage — validation",
    status: "failed",
    progress: 18,
    created_at: day(2),
    task_metadata: {
      model_type: "rtdetr-l.pt",
      training_task_name: "Car damage",
      dataset_name: "Damage (val)",
    },
  },
  {
    id: 8005,
    name: "Solar panels — aerial set",
    status: "pending",
    progress: 0,
    created_at: day(0),
    task_metadata: {
      model_type: "yolo11s.pt",
      training_task_name: "Solar panels",
      dataset_name: "Aerial inspections",
    },
  },
  {
    id: 8006,
    name: "Road signs v2 — city B",
    status: "completed",
    progress: 100,
    created_at: day(2),
    task_metadata: {
      model_type: "yolo11m.pt",
      training_task_name: "Road signs v2",
      dataset_name: "Road signs — City B",
      collection_name: "RGB",
      annotation_file_name: "road_signs_v1.coco.json",
      results: { precision: 0.881, recall: 0.842, f1_score: 0.861, images_processed: 310, predictions_count: 1820, has_ground_truth: true },
    },
  },
  {
    id: 8007,
    name: "Pothole detection — highway",
    status: "completed",
    progress: 100,
    created_at: day(5),
    task_metadata: {
      model_type: "yolo11n.pt",
      training_task_name: "Pothole detection",
      dataset_name: "Potholes — Highway",
      annotation_file_name: "potholes_gt.coco.json",
      results: { precision: 0.792, recall: 0.731, f1_score: 0.760, images_processed: 540, predictions_count: 980, has_ground_truth: true },
    },
  },
  {
    id: 8008,
    name: "Road signs v2 — night set",
    status: "completed",
    progress: 100,
    created_at: day(6),
    task_metadata: {
      model_type: "yolo11m.pt",
      training_task_name: "Road signs v2",
      dataset_name: "Road signs — Night",
      annotation_file_name: "road_signs_v2_night.coco.json",
      results: { precision: 0.722, recall: 0.681, f1_score: 0.701, images_processed: 180, predictions_count: 612, has_ground_truth: true },
    },
  },
  {
    id: 8009,
    name: "Pothole detection — city A (no GT)",
    status: "completed",
    progress: 100,
    created_at: day(1),
    task_metadata: {
      model_type: "yolo11n.pt",
      training_task_name: "Pothole detection",
      dataset_name: "Potholes — City A",
      results: { has_ground_truth: false, predictions_count: 422, images_processed: 210 },
    },
  },
  {
    id: 8010,
    name: "Pothole detection — highway (v2 GT)",
    status: "completed",
    progress: 100,
    created_at: day(2),
    task_metadata: {
      model_type: "yolo11n.pt",
      training_task_name: "Pothole detection",
      dataset_name: "Potholes — Highway",
      annotation_file_name: "potholes_gt_v2.coco.json",
      results: { precision: 0.811, recall: 0.752, f1_score: 0.781, images_processed: 540, predictions_count: 1024, has_ground_truth: true },
    },
  },
];
