"""Add image collections support

Revision ID: 5310e9164122
Revises: add_missing_annotation_columns
Create Date: 2025-08-23 09:57:32.609550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5310e9164122'
down_revision: Union[str, None] = 'add_missing_annotation_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_annotation_classes_annotation_file_id'), 'annotation_classes', ['annotation_file_id'], unique=False)
    op.alter_column('annotation_files', 'is_processed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('annotation_files', 'processing_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_annotation_files_dataset_id'), 'annotation_files', ['dataset_id'], unique=False)
    op.drop_column('annotation_files', 'file_path')
    op.alter_column('annotations', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_annotations_bbox'), table_name='annotations')
    op.create_index(op.f('ix_annotations_dataset_id'), 'annotations', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_annotations_image_id'), 'annotations', ['image_id'], unique=False)
    op.add_column('images', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_images_collection_id'), 'images', ['collection_id'], unique=False)
    op.create_index(op.f('ix_images_dataset_id'), 'images', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_images_file_name'), 'images', ['file_name'], unique=False)
    op.create_foreign_key(None, 'images', 'image_collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_index(op.f('ix_images_file_name'), table_name='images')
    op.drop_index(op.f('ix_images_dataset_id'), table_name='images')
    op.drop_index(op.f('ix_images_collection_id'), table_name='images')
    op.drop_column('images', 'collection_id')
    op.drop_index(op.f('ix_annotations_image_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_dataset_id'), table_name='annotations')
    op.create_index(op.f('ix_annotations_bbox'), 'annotations', ['bbox_x', 'bbox_y', 'bbox_width', 'bbox_height'], unique=False)
    op.alter_column('annotations', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('annotation_files', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_annotation_files_dataset_id'), table_name='annotation_files')
    op.alter_column('annotation_files', 'processing_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('annotation_files', 'is_processed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_annotation_classes_annotation_file_id'), table_name='annotation_classes')
    # ### end Alembic commands ###
