"""Add annotation_file_images table for image coverage tracking

Revision ID: dc723c15f33d
Revises: drop_dataset_annotation_count
Create Date: 2025-09-03 10:49:22.932660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc723c15f33d'
down_revision: Union[str, None] = 'drop_dataset_annotation_count'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_file_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annotation_file_id', sa.String(), nullable=True),
    sa.Column('coco_image_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('dataset_image_id', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annotation_file_id'], ['annotation_files.id'], ),
    sa.ForeignKeyConstraint(['dataset_image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_file_images_annotation_file_id'), 'annotation_file_images', ['annotation_file_id'], unique=False)
    op.create_index(op.f('ix_annotation_file_images_coco_image_id'), 'annotation_file_images', ['coco_image_id'], unique=False)
    op.create_index(op.f('ix_annotation_file_images_dataset_image_id'), 'annotation_file_images', ['dataset_image_id'], unique=False)
    op.create_index(op.f('ix_annotation_file_images_id'), 'annotation_file_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_file_images_id'), table_name='annotation_file_images')
    op.drop_index(op.f('ix_annotation_file_images_dataset_image_id'), table_name='annotation_file_images')
    op.drop_index(op.f('ix_annotation_file_images_coco_image_id'), table_name='annotation_file_images')
    op.drop_index(op.f('ix_annotation_file_images_annotation_file_id'), table_name='annotation_file_images')
    op.drop_table('annotation_file_images')
    # ### end Alembic commands ###
